services:
  - type: web
    name: ctc-flowise-slack
    region: oregon
    plan: starter
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash start.sh"
    autoDeploy: true
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: ctc-celery-redis
          type: redis
          property: connectionString
  - type: web
    name: ctc-celery-flower
    region: oregon
    plan: free
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery flower --app tasks --loglevel info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: ctc-celery-redis
          property: connectionString
  - type: redis
    name: ctc-celery-redis
    region: oregon
    plan: free
    maxmemoryPolicy: noeviction # recommended policy for queues
    ipAllowList: [] # only allow internal connections